package eu.neilalexander.yggdrasil

import android.content.Intent
import android.net.VpnService
import android.net.wifi.WifiManager
import android.os.Build
import android.os.ParcelFileDescriptor
import android.system.OsConstants
import android.util.Log
import androidx.localbroadcastmanager.content.LocalBroadcastManager
import androidx.preference.PreferenceManager
import eu.neilalexander.yggdrasil.YggStateReceiver.Companion.YGG_STATE_INTENT
import mobile.Yggdrasil
import org.json.JSONArray
import java.io.FileInputStream
import java.io.FileOutputStream
import java.net.DatagramPacket
import java.net.DatagramSocket
import java.net.InetAddress
import java.util.concurrent.LinkedBlockingQueue
import java.util.concurrent.atomic.AtomicBoolean
import kotlin.concurrent.thread


private const val TAG = "PacketTunnelProvider"
const val SERVICE_NOTIFICATION_ID = 1000

// Default upstream DNS server — user's dnsmasq on the home server.
// Can be overridden in the DNS settings screen via KEY_FORCE_DNS_UPSTREAM.
const val DEFAULT_FORCE_DNS_UPSTREAM = "20b:14e7:9d48:1c5f:490:56b1:6e5a:6ee9"

// Fake DNS server IP used by the DNS hijacking mechanism.
// This address is inside the Yggdrasil 0200::/7 range but is not a real
// Yggdrasil node — it exists only as a sink for DNS queries generated by
// the Android system resolver. DNS packets destined for this IP are
// intercepted by the VPN reader thread and forwarded to the upstream
// dnsmasq via a DatagramSocket.
private const val FAKE_DNS_IP = "200::53"

// A captured DNS query extracted from a TUN packet. Forwarded to the
// upstream DNS server via a DatagramSocket; the response is wrapped in
// a new IPv6/UDP packet addressed back to the client.
// Declared at file level because Kotlin does not allow nested class
// declarations inside an `inner class`.
private data class DnsQuery(
    val clientIp: ByteArray,   // 16 bytes (IPv6 source address)
    val clientPort: Int,        // UDP source port (resolver's ephemeral port)
    val dnsPayload: ByteArray   // Raw DNS query bytes
)

open class PacketTunnelProvider: VpnService() {
    companion object {
        const val STATE_INTENT = "eu.neilalexander.yggdrasil.PacketTunnelProvider.STATE_MESSAGE"

        const val ACTION_START = "eu.neilalexander.yggdrasil.PacketTunnelProvider.START"
        const val ACTION_STOP = "eu.neilalexander.yggdrasil.PacketTunnelProvider.STOP"
        const val ACTION_TOGGLE = "eu.neilalexander.yggdrasil.PacketTunnelProvider.TOGGLE"
        const val ACTION_CONNECT = "eu.neilalexander.yggdrasil.PacketTunnelProvider.CONNECT"
    }

    private var yggdrasil = Yggdrasil()
    private var started = AtomicBoolean()

    private lateinit var config: ConfigurationProxy

    private var readerThread: Thread? = null
    private var writerThread: Thread? = null
    private var updateThread: Thread? = null

    private var dnsHijacker: DnsHijacker? = null

    private var parcel: ParcelFileDescriptor? = null
    private var readerStream: FileInputStream? = null
    private var writerStream: FileOutputStream? = null
    private var multicastLock: WifiManager.MulticastLock? = null

    override fun onCreate() {
        super.onCreate()
        config = ConfigurationProxy(applicationContext)
    }

    override fun onDestroy() {
        super.onDestroy()
        stop()
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent == null) {
            Log.d(TAG, "Intent is null")
            return START_NOT_STICKY
        }
        val preferences = PreferenceManager.getDefaultSharedPreferences(this.baseContext)
        val enabled = preferences.getBoolean(PREF_KEY_ENABLED, false)
        return when (intent.action ?: ACTION_STOP) {
            ACTION_STOP -> {
                Log.d(TAG, "Stopping...")
                stop(); START_NOT_STICKY
            }
            ACTION_CONNECT -> {
                Log.d(TAG, "Connecting...")
                if (started.get()) {
                    connect()
                } else {
                    start()
                }
                START_STICKY
            }
            ACTION_TOGGLE -> {
                Log.d(TAG, "Toggling...")
                if (started.get()) {
                    stop(); START_NOT_STICKY
                } else {
                    start(); START_STICKY
                }
            }
            else -> {
                if (!enabled) {
                    Log.d(TAG, "Service is disabled")
                    return START_NOT_STICKY
                }
                Log.d(TAG, "Starting...")
                start(); START_STICKY
            }
        }
    }

    private fun start() {
        if (!started.compareAndSet(false, true)) {
            return
        }

        val notification = createServiceNotification(this, State.Enabled)
        startForeground(SERVICE_NOTIFICATION_ID, notification)

        // Acquire multicast lock
        val wifi = applicationContext.getSystemService(WIFI_SERVICE) as WifiManager
        multicastLock = wifi.createMulticastLock("Yggdrasil").apply {
            setReferenceCounted(false)
            acquire()
        }

        Log.d(TAG, config.getJSON().toString())
        yggdrasil.startJSON(config.getJSONByteArray())

        val address = yggdrasil.addressString
        val builder = Builder()
            .addAddress(address, 7)
            .addRoute("200::", 7)
            // We do this to trick the DNS-resolver into thinking that we have "regular" IPv6,
            // and therefore we need to resolve AAAA DNS-records.
            // See: https://android.googlesource.com/platform/bionic/+/refs/heads/master/libc/dns/net/getaddrinfo.c#1935
            // and: https://android.googlesource.com/platform/bionic/+/refs/heads/master/libc/dns/net/getaddrinfo.c#365
            // If we don't do this the DNS-resolver just doesn't do DNS-requests with record type AAAA,
            // and we can't use DNS with Yggdrasil addresses.
            .addRoute("2000::", 128)
            .allowFamily(OsConstants.AF_INET)
            .setBlocking(true)
            .setMtu(yggdrasil.mtu.toInt())
            .setSession("Yggdrasil")
        // On Android API 29+ apps can opt-in/out to using metered networks.
        // If we don't set metered status of VPN it is considered as metered.
        // If we set it to false, then it will inherit this status from underlying network.
        // See: https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            builder.setMetered(false)
        }

        val preferences = PreferenceManager.getDefaultSharedPreferences(this.baseContext)

        // ---- MODIFICATION START ----
        // "Force system DNS" mode: uses DNS hijacking to intercept all DNS
        // queries from the Android system resolver and forward them through
        // the Yggdrasil tunnel to a user-configured upstream DNS server
        // (default = home dnsmasq on the Yggdrasil network).
        //
        // How it works:
        //   1. A fake IP (200::53) inside the Yggdrasil 0200::/7 range is
        //      registered as the VPN's DNS server via addDnsServer().
        //   2. The existing addRoute("200::", 7) already routes this IP
        //      through the VPN tunnel.
        //   3. When the Android system resolver sends a DNS query to
        //      200::53:53, the packet enters the TUN.
        //   4. The reader thread intercepts the packet (before passing it
        //      to Yggdrasil) and extracts the DNS query payload.
        //   5. The query is forwarded via a DatagramSocket to the upstream
        //      dnsmasq (which is reachable over the Yggdrasil network).
        //   6. The response is received, wrapped in a new IPv6/UDP packet
        //      (source=200::53:53, destination=original client), and written
        //      back to the TUN. The kernel delivers it to the resolver.
        //
        // Why this approach:
        //   Android 13's "Private DNS" (DoT) feature intercepts DNS queries
        //   at the resolver level before VpnService.addDnsServer() can
        //   redirect them. The previous approach (binding a local DNS proxy
        //   on port 53) failed because port 53 is a privileged port that
        //   Android doesn't allow non-root apps to bind to (EACCES).
        //   DNS hijacking at the VPN packet level works without root and
        //   without binding to any port — the interception happens in the
        //   reader thread, which just reads raw IP packets from the TUN.
        //
        // NOTE: allowBypass() is intentionally NOT called when force DNS is
        // on, because allowBypass() lets privileged apps skip the VPN
        // entirely, which defeats the purpose of forcing DNS through the
        // tunnel.
        val forceDnsEnabled = preferences.getBoolean(KEY_FORCE_SYSTEM_DNS, true)
        val forceDnsUpstream = preferences.getString(
            KEY_FORCE_DNS_UPSTREAM, DEFAULT_FORCE_DNS_UPSTREAM
        ) ?: DEFAULT_FORCE_DNS_UPSTREAM

        if (forceDnsEnabled && forceDnsUpstream.isNotEmpty()) {
            Log.i(TAG, "Force system DNS enabled (hijack mode), upstream=$forceDnsUpstream")
            try {
                dnsHijacker = DnsHijacker(upstream = forceDnsUpstream)
                dnsHijacker?.start()
                // Register the fake DNS IP as the VPN's DNS server.
                // Android's resolver will send DNS queries to this IP:53.
                // No addRoute() is needed here because the existing
                // addRoute("200::", 7) already covers 200::53.
                builder.addDnsServer(FAKE_DNS_IP)
                Log.i(TAG, "DNS hijacking enabled, fake DNS IP=$FAKE_DNS_IP -> $forceDnsUpstream:53")
            } catch (e: Exception) {
                Log.e(TAG, "Failed to start DNS hijacking: ${e.message}", e)
                // Fall back to the old behaviour (forward to upstream directly).
                // This likely won't work due to Private DNS, but it's better
                // than nothing.
                builder.addDnsServer(forceDnsUpstream)
            }
        } else {
            // Legacy behaviour: forward directly to the configured DNS servers.
            val serverString = preferences.getString(KEY_DNS_SERVERS, "")
            if (serverString!!.isNotEmpty()) {
                val servers = serverString.split(",")
                if (servers.isNotEmpty()) {
                    servers.forEach {
                        Log.i(TAG, "Using DNS server $it")
                        builder.addDnsServer(it)
                    }
                }
            }
        }
        // ---- MODIFICATION END ----

        if (preferences.getBoolean(KEY_ENABLE_CHROME_FIX, false)) {
            builder.addRoute("2001:4860:4860::8888", 128)
        }

        parcel = builder.establish()
        val parcel = parcel
        if (parcel == null || !parcel.fileDescriptor.valid()) {
            stop()
            return
        }

        readerStream = FileInputStream(parcel.fileDescriptor)
        writerStream = FileOutputStream(parcel.fileDescriptor)

        readerThread = thread {
            reader()
        }
        writerThread = thread {
            writer()
        }
        updateThread = thread {
            updater()
        }

        var intent = Intent(YGG_STATE_INTENT)
        intent.putExtra("state", STATE_ENABLED)
        LocalBroadcastManager.getInstance(this).sendBroadcast(intent)
    }

    private fun stop() {
        if (!started.compareAndSet(true, false)) {
            return
        }

        yggdrasil.stop()

        dnsHijacker?.stop()
        dnsHijacker = null

        readerStream?.let {
            it.close()
            readerStream = null
        }
        writerStream?.let {
            it.close()
            writerStream = null
        }
        parcel?.let {
            it.close()
            parcel = null
        }

        readerThread?.let {
            it.interrupt()
            readerThread = null
        }
        writerThread?.let {
            it.interrupt()
            writerThread = null
        }
        updateThread?.let {
            it.interrupt()
            updateThread = null
        }

        var intent = Intent(STATE_INTENT)
        intent.putExtra("type", "state")
        intent.putExtra("started", false)
        LocalBroadcastManager.getInstance(this).sendBroadcast(intent)

        intent = Intent(YGG_STATE_INTENT)
        intent.putExtra("state", STATE_DISABLED)
        LocalBroadcastManager.getInstance(this).sendBroadcast(intent)

        stopForeground(true)
        stopSelf()
        multicastLock?.release()
    }

    private fun connect() {
        if (!started.get()) {
            return
        }
        yggdrasil.retryPeersNow()
    }

    private fun updater() {
        try {
            Thread.sleep(500)
        } catch (_: InterruptedException) {
            return
        }
        var lastStateUpdate = System.currentTimeMillis()
        updates@ while (started.get()) {
            val treeJSON = yggdrasil.treeJSON
            if ((application as  GlobalApplication).needUiUpdates()) {
                val intent = Intent(STATE_INTENT)
                intent.putExtra("type", "state")
                intent.putExtra("started", true)
                intent.putExtra("ip", yggdrasil.addressString)
                intent.putExtra("subnet", yggdrasil.subnetString)
                intent.putExtra("pubkey", yggdrasil.publicKeyString)
                intent.putExtra("peers", yggdrasil.peersJSON)
                LocalBroadcastManager.getInstance(this).sendBroadcast(intent)
            }
            val curTime = System.currentTimeMillis()
            if (lastStateUpdate + 10000 < curTime) {
                val intent = Intent(YGG_STATE_INTENT)
                var state = STATE_ENABLED
                if (yggdrasil.routingEntries > 0) {
                    state = STATE_CONNECTED
                }
                if (treeJSON != null && treeJSON != "null") {
                    val treeState = JSONArray(treeJSON)
                    val count = treeState.length()
                    if (count > 1)
                        state = STATE_CONNECTED
                }
                intent.putExtra("state", state)
                LocalBroadcastManager.getInstance(this).sendBroadcast(intent)
                lastStateUpdate = curTime
            }

            if (Thread.currentThread().isInterrupted) {
                break@updates
            }
            if (sleep()) return
        }
    }

    private fun sleep(): Boolean {
        try {
            Thread.sleep(1000)
        } catch (e: InterruptedException) {
            return true
        }
        return false
    }

    /**
     * Writes a raw IP packet to the TUN interface. Thread-safe —
     * both the writer thread (forwarding Yggdrasil's outgoing packets)
     * and the DNS hijacker (injecting DNS responses) call this method.
     */
    @Synchronized
    private fun writePacketToTun(buf: ByteArray, len: Int) {
        val stream = writerStream ?: return
        if (len <= 0) return
        try {
            stream.write(buf, 0, len)
        } catch (e: Exception) {
            Log.i(TAG, "Error writing packet to TUN: $e")
        }
    }

    private fun writer() {
        val buf = ByteArray(65535)
        writes@ while (started.get()) {
            val writerStream = writerStream
            val writerThread = writerThread
            if (writerThread == null || writerStream == null) {
                Log.i(TAG, "Write thread or stream is null")
                break@writes
            }
            if (Thread.currentThread().isInterrupted || !writerStream.fd.valid()) {
                Log.i(TAG, "Write thread interrupted or file descriptor is invalid")
                break@writes
            }
            try {
                val len = yggdrasil.recvBuffer(buf)
                if (len > 0) {
                    writePacketToTun(buf, len.toInt())
                }
            } catch (e: Exception) {
                Log.i(TAG, "Error in write: $e")
                if (e.toString().contains("ENOBUFS")) {
                    //TODO Check this by some error code
                    //More info about this: https://github.com/AdguardTeam/AdguardForAndroid/issues/724
                    continue
                }
                break@writes
            }
        }
        writerStream?.let {
            it.close()
            writerStream = null
        }
    }

    private fun reader() {
        val b = ByteArray(65535)
        reads@ while (started.get()) {
            val readerStream = readerStream
            val readerThread = readerThread
            if (readerThread == null || readerStream == null) {
                Log.i(TAG, "Read thread or stream is null")
                break@reads
            }
            if (Thread.currentThread().isInterrupted ||!readerStream.fd.valid()) {
                Log.i(TAG, "Read thread interrupted or file descriptor is invalid")
                break@reads
            }
            try {
                val n = readerStream.read(b)
                // Try to intercept DNS queries destined for our fake DNS IP.
                // If intercepted, the packet is NOT forwarded to Yggdrasil —
                // it's handled by the DnsHijacker, which forwards the query
                // to the upstream dnsmasq and injects the response back into
                // the TUN via writePacketToTun().
                val hijacker = dnsHijacker
                if (hijacker != null && hijacker.maybeIntercept(b, n)) {
                    continue
                }
                yggdrasil.sendBuffer(b, n.toLong())
            } catch (e: Exception) {
                Log.i(TAG, "Error in sendBuffer: $e")
                break@reads
            }
        }
        readerStream?.let {
            it.close()
            readerStream = null
        }
    }

    /**
     * DNS Hijacker — intercepts DNS queries destined for a fake IP
     * (200::53) and forwards them to an upstream DNS server over the
     * Yggdrasil network.
     *
     * Why this exists:
     *   Android 13's "Private DNS" (DoT) feature intercepts DNS queries
     *   at the resolver level *before* VpnService.addDnsServer() can
     *   redirect them. The previous approach (running a local DNS proxy
     *   on port 53) failed because port 53 is a privileged port on
     *   Android — non-root apps (including VpnService apps) get EACCES
     *   when trying to bind to it.
     *
     *   DNS hijacking at the VPN packet level avoids both problems:
     *   - No port binding required — interception happens in the reader
     *     thread, which reads raw IP packets from the TUN.
     *   - Private DNS is bypassed because the resolver sends plain DNS
     *     to our fake IP (which doesn't support DoT, so Private DNS
     *     falls back to plain DNS).
     *
     * How it works:
     *   1. The fake IP (200::53) is registered as the VPN's DNS server.
     *   2. The system resolver sends DNS queries to 200::53:53.
     *   3. These packets enter the TUN (because 200::53 is in the
     *      0200::/7 range, which is routed through the VPN).
     *   4. The reader thread calls maybeIntercept() on each packet.
     *      If the packet is an IPv6/UDP packet destined for 200::53:53,
     *      it's extracted and queued for forwarding.
     *   5. The forwarder thread takes queries from the queue and sends
     *      them via DatagramSocket to the upstream DNS server (e.g.,
     *      dnsmasq on the home server, reachable via Yggdrasil).
     *   6. When the response arrives, it's wrapped in a new IPv6/UDP
     *      packet (source=200::53:53, destination=original client) and
     *      written to the TUN via writePacketToTun(). The kernel
     *      delivers it to the system resolver.
     *
     * Why only UDP:
     *   The Android system resolver uses UDP for almost everything; TCP
     *   is only used as a fallback for truncated responses. Keeping the
     *   implementation UDP-only makes the hijacker small and easy to
     *   audit. If a response has the TC (truncated) bit set, the
     *   resolver will retry over TCP against the same IP:53 — we don't
     *   currently handle TCP, but dnsmasq typically keeps UDP responses
     *   under 512 bytes by using EDNS0.
     */
    private inner class DnsHijacker(
        private val upstream: String
    ) {
        private val running = AtomicBoolean(false)
        private val fakeDnsIpBytes: ByteArray = InetAddress.getByName(FAKE_DNS_IP).address
        private var forwarderThread: Thread? = null
        private val queryQueue = LinkedBlockingQueue<DnsQuery>()

        fun start() {
            running.set(true)
            forwarderThread = thread(name = "DnsHijacker-Forwarder", isDaemon = true) {
                forwarder()
            }
            Log.i(TAG, "DnsHijacker started, fake DNS IP=$FAKE_DNS_IP, upstream=$upstream")
        }

        fun stop() {
            running.set(false)
            forwarderThread?.interrupt()
        }

        /**
         * Checks if a raw IP packet (read from the TUN) is a DNS query
         * destined for our fake DNS server (200::53:53). If yes, extracts
         * the query and queues it for forwarding, and returns true so the
         * caller (reader thread) knows NOT to pass the packet to Yggdrasil.
         *
         * Returns false for all other packets (non-DNS, non-UDP, wrong
         * destination, IPv4, etc.), which should be passed to Yggdrasil
         * normally.
         */
        fun maybeIntercept(packet: ByteArray, length: Int): Boolean {
            // Minimum: 40 (IPv6 header) + 8 (UDP header) + 12 (DNS header) = 60 bytes
            if (length < 60) return false

            // Check IPv6: version 6 (top 4 bits of first byte)
            if ((packet[0].toInt() ushr 4) and 0x0F != 6) return false

            // Check Next Header = 17 (UDP) at byte 6
            if (packet[6].toInt() and 0xFF != 17) return false

            // Check destination IP (bytes 24-39) == fake DNS IP
            // Quick check: first byte of 200::53 is 0x02
            if (packet[24] != fakeDnsIpBytes[0]) return false
            for (i in 1 until 16) {
                if (packet[24 + i] != fakeDnsIpBytes[i]) return false
            }

            // Check destination port (bytes 46-47) == 53
            val dstPort = ((packet[46].toInt() and 0xFF) shl 8) or (packet[47].toInt() and 0xFF)
            if (dstPort != 53) return false

            // This is a DNS query for our fake server. Extract the details.
            val srcIp = packet.copyOfRange(8, 24)      // IPv6 source address
            val srcPort = ((packet[40].toInt() and 0xFF) shl 8) or
                          (packet[41].toInt() and 0xFF)
            val dnsPayload = packet.copyOfRange(48, length)

            queryQueue.offer(DnsQuery(srcIp, srcPort, dnsPayload))
            Log.d(TAG, "DNS query intercepted: srcPort=$srcPort, queryLen=${dnsPayload.size}")
            return true
        }

        private fun forwarder() {
            val upstreamAddr = InetAddress.getByName(upstream)
            Log.i(TAG, "DnsHijacker forwarder ready, upstream=$upstreamAddr")

            while (running.get()) {
                val query = try {
                    queryQueue.take()
                } catch (e: InterruptedException) {
                    break
                }

                // Forward each query in its own thread so a slow query
                // doesn't block the forwarder.
                thread(name = "DnsHijacker-Query", isDaemon = true) {
                    try {
                        val fwdPacket = DatagramPacket(
                            query.dnsPayload, query.dnsPayload.size,
                            upstreamAddr, 53
                        )
                        val respBuf = ByteArray(4096)
                        val respPacket = DatagramPacket(respBuf, respBuf.size)

                        // Create a fresh socket per query. The socket is
                        // NOT protected — VpnService apps' unprotected
                        // sockets are routed through the VPN by default,
                        // so the outbound packet enters the TUN, is handled
                        // by the Yggdrasil Go runtime, and reaches the
                        // upstream dnsmasq over the Yggdrasil network.
                        // (The Go runtime's own peer sockets are separately
                        // protected by the Go code to avoid routing loops.)
                        val qSock = DatagramSocket()
                        qSock.soTimeout = 4000
                        try {
                            qSock.send(fwdPacket)
                            qSock.receive(respPacket)
                            val respLen = respPacket.length
                            val dnsResp = ByteArray(respLen)
                            System.arraycopy(respBuf, 0, dnsResp, 0, respLen)

                            // Construct an IPv6/UDP response packet:
                            //   source = 200::53:53 (fake DNS server)
                            //   destination = client IP:client port (original resolver)
                            val responsePacket = buildIpv6UdpPacket(
                                srcIp = fakeDnsIpBytes,
                                srcPort = 53,
                                dstIp = query.clientIp,
                                dstPort = query.clientPort,
                                payload = dnsResp
                            )

                            // Write the response to the TUN. The kernel
                            // will deliver it to the system resolver.
                            writePacketToTun(responsePacket, responsePacket.size)
                            Log.d(TAG, "DNS response injected: dstPort=${query.clientPort}, respLen=$respLen")
                        } finally {
                            qSock.close()
                        }
                    } catch (e: Exception) {
                        Log.w(TAG, "DnsHijacker query forward failed: ${e.message}")
                    }
                }
            }
        }

        /**
         * Builds a complete IPv6/UDP packet from the given parameters.
         * Computes the UDP checksum (mandatory for IPv6/UDP per RFC 2460).
         *
         * IPv6 header layout (40 bytes):
         *   [0]  Version(4) + Traffic Class upper(4)
         *   [1]  Traffic Class lower(4) + Flow Label upper(4)
         *   [2-3]  Flow Label lower(16)
         *   [4-5]  Payload Length (16 bits) = UDP segment size
         *   [6]  Next Header (8 bits) = 17 (UDP)
         *   [7]  Hop Limit (8 bits) = 64
         *   [8-23]  Source Address (128 bits)
         *   [24-39]  Destination Address (128 bits)
         *
         * UDP header layout (8 bytes, starts at offset 40):
         *   [40-41]  Source Port (16 bits)
         *   [42-43]  Destination Port (16 bits)
         *   [44-45]  Length (16 bits) = 8 + payload size
         *   [46-47]  Checksum (16 bits) — computed over pseudo-header
         *
         * UDP payload starts at offset 48.
         */
        private fun buildIpv6UdpPacket(
            srcIp: ByteArray,
            srcPort: Int,
            dstIp: ByteArray,
            dstPort: Int,
            payload: ByteArray
        ): ByteArray {
            val udpLen = 8 + payload.size
            val totalLen = 40 + udpLen  // IPv6 header (40) + UDP header (8) + payload

            val packet = ByteArray(totalLen)

            // ---- IPv6 header (40 bytes) ----
            // Version (4 bits) = 6, Traffic Class (8 bits) = 0, Flow Label (20 bits) = 0
            packet[0] = 0x60.toByte()
            packet[1] = 0
            packet[2] = 0
            packet[3] = 0
            // Payload Length (16 bits) = UDP segment size (header + data)
            packet[4] = ((udpLen ushr 8) and 0xFF).toByte()
            packet[5] = (udpLen and 0xFF).toByte()
            // Next Header (8 bits) = 17 (UDP)
            packet[6] = 17
            // Hop Limit (8 bits) = 64
            packet[7] = 64
            // Source Address (128 bits / 16 bytes)
            System.arraycopy(srcIp, 0, packet, 8, 16)
            // Destination Address (128 bits / 16 bytes)
            System.arraycopy(dstIp, 0, packet, 24, 16)

            // ---- UDP header (8 bytes, at offset 40) ----
            // Source Port
            packet[40] = ((srcPort ushr 8) and 0xFF).toByte()
            packet[41] = (srcPort and 0xFF).toByte()
            // Destination Port
            packet[42] = ((dstPort ushr 8) and 0xFF).toByte()
            packet[43] = (dstPort and 0xFF).toByte()
            // Length
            packet[44] = ((udpLen ushr 8) and 0xFF).toByte()
            packet[45] = (udpLen and 0xFF).toByte()
            // Checksum (placeholder — computed below)
            packet[46] = 0
            packet[47] = 0

            // ---- UDP payload (at offset 48) ----
            System.arraycopy(payload, 0, packet, 48, payload.size)

            // Compute UDP checksum (mandatory for IPv6/UDP, RFC 2460 Section 8.1)
            val checksum = computeUdpChecksum(srcIp, dstIp, packet, 40, udpLen)
            packet[46] = ((checksum ushr 8) and 0xFF).toByte()
            packet[47] = (checksum and 0xFF).toByte()

            return packet
        }

        /**
         * Computes the UDP checksum over the IPv6 pseudo-header + UDP
         * header + UDP payload. Returns the one's complement of the sum.
         * If the result is 0, returns 0xFFFF (per RFC 768).
         *
         * Pseudo-header (RFC 2460 Section 8.1):
         *   - Source Address (16 bytes)
         *   - Destination Address (16 bytes)
         *   - Upper-Layer Packet Length (32 bits) = UDP Length
         *   - Zero (24 bits) + Next Header (8 bits) = 0x00000011
         */
        private fun computeUdpChecksum(
            srcIp: ByteArray,
            dstIp: ByteArray,
            packet: ByteArray,
            udpOffset: Int,
            udpLen: Int
        ): Int {
            var sum: Long = 0

            // Pseudo-header: Source Address (16 bytes, summed as 8 x 16-bit words)
            for (i in 0 until 16 step 2) {
                sum += ((srcIp[i].toInt() and 0xFF).toLong() shl 8) or
                       (srcIp[i + 1].toInt() and 0xFF).toLong()
            }
            // Pseudo-header: Destination Address (16 bytes, summed as 8 x 16-bit words)
            for (i in 0 until 16 step 2) {
                sum += ((dstIp[i].toInt() and 0xFF).toLong() shl 8) or
                       (dstIp[i + 1].toInt() and 0xFF).toLong()
            }
            // Pseudo-header: Upper-Layer Packet Length (32 bits)
            // UDP length fits in 16 bits, so the upper 16 bits are 0.
            sum += udpLen.toLong()
            // Pseudo-header: Zero (24 bits) + Next Header (8 bits = 17)
            // Upper 16 bits are 0, lower 16 bits are 0x0011 = 17.
            sum += 17

            // UDP header + data (summed as 16-bit words)
            val end = udpOffset + udpLen
            var i = udpOffset
            while (i < end - 1) {
                sum += ((packet[i].toInt() and 0xFF).toLong() shl 8) or
                       (packet[i + 1].toInt() and 0xFF).toLong()
                i += 2
            }
            if (i < end) {
                // Odd byte — pad with zero on the right
                sum += (packet[i].toInt() and 0xFF).toLong() shl 8
            }

            // Fold 32-bit sum to 16 bits
            while (sum ushr 16 != 0L) {
                sum = (sum and 0xFFFF) + (sum ushr 16)
            }

            // One's complement
            val result = (sum.toInt() and 0xFFFF).inv() and 0xFFFF
            // Per RFC 768, a computed checksum of 0 is transmitted as 0xFFFF
            return if (result == 0) 0xFFFF else result
        }
    }
}
